export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CHANGE_CONVERSION_TYPE = 'CHANGE_CONVERSION_TYPE';

export const UPDATE_PLAYERS_INIT = 'UPDATE_PLAYERS_INIT';
export const UPDATE_PLAYERS_SUCCESS = 'UPDATE_PLAYERS_SUCCESS';
export const UPDATE_PLAYERS_FAILED = 'UPDATE_PLAYERS_FAILED';

export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';

export const UPDATE_PINNED_PLAYERS = 'UPDATE_PINNED_PLAYERS';

export const PLAYER_QUICK_NAV_DETAILS = 'PLAYER_QUICK_NAV_DETAILS';

export const CHANGE_CURRENT_GO_BACK_ROUTE_FROM_PROFILE = 'CHANGE_CURRENT_GO_BACK_ROUTE_FROM_PROFILE';
